name: flutter_credit_card
description: A Credit Card widget package, support entering card details, card flip animation.
version: 3.0.4
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  font_awesome_flutter: ^10.2.1
  mobile_l10n:
    git:
      url: https://human-forest:Nytt1ycZ7CppE1jX_eUB@gitlab.com/human-forest/human-forest-mobile-app/mobile_l10n.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - icons/
  fonts:
    - family: halter
      fonts:
        - asset: font/halter.ttf
